### ISSUE TITLE
[Request] Display week number

### ISSUE THREAD

**Issue by 17406** [uvarov-frontend/vanilla-calendar#1]
I was wondering if there are any plans to support the option to enable week numbers in the calendar? Not sure about the rest of the world, but here in Norway we very often refer to dates using week numbers. The ability to enable this would therefore be very useful.

**Comment by 17406** [comment]
Ah, that's exactly what I mean. Wonderful :).

**Comment by uvarov-frontend** [comment]
What you need is implemented in version [1.4.3](https://www.npmjs.com/package/@uvarov.frontend/vanilla-calendar). See the `settings.visibility.weekNumbers` parameter in the documentation and the "**Show week numbers**" in the [demo](https://vanilla-calendar.frontend.uvarov.tech/en/demos/).
