### ISSUE TITLE
Anual Layout

### ISSUE THREAD

**Issue by robsontenorio** [uvarov-frontend/vanilla-calendar#100]
Hi, great job!

**Is it possible to make this kind of annual layout?**

<img width="1127" alt="image" src="https://github.com/uvarov-frontend/vanilla-calendar/assets/118955/e8f2e57a-bb1f-44c7-9259-0f64ac2e2b24">

<p>... </p>

**I have tried `type="multiple"` and `months="12"` , but I got this.**   Maybe some setting like `rows/columns` ?

<img width="1225" alt="image" src="https://github.com/uvarov-frontend/vanilla-calendar/assets/118955/486c1df8-85f1-4930-a261-14b27d428e3f">

**Comment by uvarov-frontend** [comment]
Hi, you can manage the columns via css using grid.

**Comment by robsontenorio** [comment]
@uvarov-frontend Thanks!

For my future self:

**Using Tailwind**

```css
.vanilla-calendar {
    @apply w-fit
}

.vanilla-calendar-grid {
    @apply flex flex-wrap justify-around
}
```

```js
{ settings: { lang: 'pt-BR'}, type: 'multiple', months: 12, }
```

<img width="1297" alt="image" src="https://github.com/uvarov-frontend/vanilla-calendar/assets/118955/fa1ed039-fe3b-4436-b15e-e7a172725f30">
