### ISSUE TITLE
[Question] Month Step

### ISSUE THREAD

**Issue by robsontenorio** [uvarov-frontend/vanilla-calendar#101]
Considering the layout  with multiples months at #100 , is there any workaround to control `month steps` when arrows is clicked?

Example:
- If a have `months=X ` it would be useful to jump `X` months forward/backward when arrows are clicked.

**Comment by uvarov-frontend** [comment]
const options = {
  type: "multiple",
  months: 12,
  actions: {
    clickArrow(event, year, month) {
      const isPrev = event.target.closest('[data-calendar-arrow="prev"]');
      const date = new Date(year, month);
      date.setMonth(isPrev ? date.getMonth() - 11 : date.getMonth() + 11);
      calendar.settings.selected.year = date.getFullYear();
      calendar.settings.selected.month = date.getMonth();
      calendar.update();
    }
  }
};

const calendar = new VanillaCalendar("#calendar", options);
calendar.init();

https://codesandbox.io/s/romantic-farrell-5mgm9d?file=/calendar.js

**Comment by robsontenorio** [comment]
@uvarov-frontend Yes, you rock! Thank you ! ❤️

**Comment by uvarov-frontend** [comment]
Add a parameter responsible for the number of months to switch, if `type: 'multiple'`.
