### ISSUE TITLE
Allow override "calendar" css class

### ISSUE THREAD

**Issue by robsontenorio** [uvarov-frontend/vanilla-calendar#102]
Just took your recent SANDBOX: https://codesandbox.io/s/romantic-farrell-5mgm9d?file=/calendar.js

It allows me combine class for "grid"

<img width="1049" alt="image" src="https://github.com/uvarov-frontend/vanilla-calendar/assets/118955/0eb699f4-09b7-40e3-83aa-cef955aa4516">

But not for "calendar". Am I missing something?

<img width="1107" alt="image" src="https://github.com/uvarov-frontend/vanilla-calendar/assets/118955/fd4da279-24a5-48c0-b6ef-bbad17603b97">

**Comment by uvarov-frontend** [comment]
Don't use several classes, it wasn't so planned, it's strange that it works with the grid.
