### ISSUE TITLE
Calendar from input - dropdown direction

### ISSUE THREAD

**Issue by ipetryszak** [uvarov-frontend/vanilla-calendar#103]
Hi, I encountered an issue while working with the calendar in input.

The current implementation doesn't determine the direction of the dropdown which results in dropping the date picker below the input - ignoring the viewport.

![Screenshot from 2023-09-01 13-26-29](https://github.com/uvarov-frontend/vanilla-calendar/assets/25117978/f1dce2c5-9bf3-407c-a4f1-82203b1aa85f)

Compared to the native input calendar which handles that scenario:

![Screenshot from 2023-09-01 13-30-39](https://github.com/uvarov-frontend/vanilla-calendar/assets/25117978/4ceba91c-7c4e-48e1-a4b2-b13496fa0433)

Is there a way to handle it or plans for that enhancement? Thanks

**Comment by uvarov-frontend** [comment]
Use a static calendar and create your own calendar output on click on any element and use the library https://popper.js.org/
