### ISSUE TITLE
Prev click with `jumpMonths`

### ISSUE THREAD

**Issue by robsontenorio** [uvarov-frontend/vanilla-calendar#113]
Hi,

What is correct setup to make `jumpMonths` work properly?

```js
const options = {
  type: "multiple",
  months: 3,
  jumpMonths: 3
};
```

It jumps forwards correctly. But not backwards.

https://codesandbox.io/s/brave-snowflake-csqfzg?file=/calendar.js

**Comment by uvarov-frontend** [comment]
I don't see the problem, is this problem really in the example you gave?

**Comment by robsontenorio** [comment]
# Initial state

<img width="746" alt="image" src="https://github.com/uvarov-frontend/vanilla-calendar/assets/118955/d47107da-7d45-4232-b9ea-37209045a6ce">

# After click NEXT (it is ok)

<img width="758" alt="image" src="https://github.com/uvarov-frontend/vanilla-calendar/assets/118955/87895562-4edb-4022-8a20-36fa10b2061e">

# Now, when you click PREV .... 

## It does not back to initial state (3 months back) .... where is November ?

<img width="775" alt="image" src="https://github.com/uvarov-frontend/vanilla-calendar/assets/118955/5e854dc0-6bfd-48be-ab41-213fa18d510c">

**Comment by uvarov-frontend** [comment]
Most likely, the reason is in the time zone, I have already encountered such errors. I'll fix it, thanks for the error message. I'll write later.

If you are interested, set a different time zone and check the reverse arrow.

**Comment by robsontenorio** [comment]
@uvarov-frontend 

Right now I reverted back to your snippet from #101 with 2.6.2 and it works. 

But not with 2.6.3

So, I don’t  believe it has to do with timezone because we aren’t on 1st or 31th

**Comment by robsontenorio** [comment]
Here is a working version: **your snippet from #101  with 2.6.2**

https://mary-ui.com/docs/components/calendar#multiple-months

**Comment by uvarov-frontend** [comment]
The problem is definitely in the time zone, since in time zones where `UTC > 0` such a problem is not observed. For example, I have `UTC+3`. In your case, one of these values ​​is `UTC-5, UTC-4, UTC-3 and UTC-2`.

In any case, I have already fixed the problem. Use v2.6.4
