### ISSUE TITLE
Is it possible to remove build/_vanilla-calendar.min.css ?

### ISSUE THREAD

**Issue by rgajadin** [uvarov-frontend/vanilla-calendar#115]
I'm trying to include vanilla-calendar.min.css into my .scss file to create a single .css output

But because of _vanilla-calendar.min.css it can't do that due to the file name being essentially the same.

Error: It's not clear which file to import. Found:
[16:32:51 ERR]   node_modules\@uvarov.frontend\vanilla-calendar\build\\_vanilla-calendar.min.css
[16:32:51 ERR]   node_modules\@uvarov.frontend\vanilla-calendar\build\vanilla-calendar.min.css

**Comment by uvarov-frontend** [comment]
node_modules@uvarov.frontend\vanilla-calendar\build_vanilla-calendar.min.css

Check the path to the file. Absent "/"

**Comment by uvarov-frontend** [comment]
I don't see this error.
https://codesandbox.io/s/intelligent-dawn-x8vqn7?file=/calendar.js

**Comment by rgajadin** [comment]
Here is a small sample to reproduce it and show what i'm trying to do 
https://codesandbox.io/p/sandbox/nice-liskov-y3kd8n?welcome=true

**Comment by uvarov-frontend** [comment]
Why do you use "@use" instead of "@import"?

```
@import "@uvarov.frontend/vanilla-calendar/build/vanilla-calendar.min.css";
@import "@uvarov.frontend/vanilla-calendar/build/themes/light.min.css";
```

https://codesandbox.io/p/sandbox/hardcore-montalcini-w5y3y6?file=/src/styles.scss:1,1-2,72

**Comment by rgajadin** [comment]
Because we are using this in a client side application. We generate a single .css file as output that contains everything inside it.

if you use @import or @use with '.css' at the end you get this as output
https://codesandbox.io/p/sandbox/hardcore-montalcini-w5y3y6?file=/dist/styles.css:1,1

which means i would also have to make those files accessible to the end user.

the _vanilla-calendar.min.css also does not have to be deleted it can also be renamed. I just said remove because i don't really see it being used anywhere.

**Comment by uvarov-frontend** [comment]
It's clear.
`_vanilla-calendar.min.css` is the old stylesheet for this calendar. I planned to remove it in future versions, but for now I left it for those who use it.
I plan to release more features and remove `_vanilla-calendar.min.css` in v2.6.5

**Comment by uvarov-frontend** [comment]
Remotely in v2.6.5
