### ISSUE TITLE
year selection in type: 'multiple'

### ISSUE THREAD

**Issue by yax3** [uvarov-frontend/vanilla-calendar#119]
Если календарь состоит из 3 месяцев, и третьим выбран январь, то при переключении года (у третьего месяца), устанавливается не актуальная дата, выбранный год смещается на два назад
![Снимок экрана от 2023-10-02 11-54-41](https://github.com/uvarov-frontend/vanilla-calendar/assets/10906780/c854d206-c8a7-4c37-9f26-fbf6ca2c9fe1)

**Comment by uvarov-frontend** [comment]
Спасибо за сообщение о проблеме. Будет исправлено в  v2.6.6
