### ISSUE TITLE
fix: documentation description error

### ISSUE THREAD

**Issue by Bkyaro** [uvarov-frontend/vanilla-calendar#12]
Hi uvarov, love your vanilla calendar it is so cool.
I found an description error in documentation website about the setting.range.enabled:
https://vanilla-calendar.frontend.uvarov.tech/en/documentation/
<img width="831" alt="image" src="https://user-images.githubusercontent.com/30712768/193205647-540f6593-1325-4b3f-9ebb-1b3199574bce.png">

**Comment by uvarov-frontend** [comment]
Hi, thanks for the kind words! I'll fix the bug in the documentation.
