### ISSUE TITLE
Display programatically selected year and month on date picker

### ISSUE THREAD

**Issue by gersonkm** [uvarov-frontend/vanilla-calendar#128]
I am currently using the 'date picker in input' functionality and need to set a new selected date programmatically. 

Here's the code I'm using for this:

```
calendar.settings.selected.dates = ["2022-10-28"];
calendar.update()
```

After updating the selected dates using the code below, how can I ensure that when opening the calendar again through the date picker in the input field, it displays the calendar for the year and month that was programmatically selected?

**Comment by uvarov-frontend** [comment]
```
calendar.settings.selected.dates = ["2023-10-28"];
calendar.HTMLInputElement.value = "2023-10-28";
calendar.update();
```

**Comment by SohanChotia** [comment]
I need this, to set a pre-selected date range in input mode. But it doesn't seem to work.

In input mode, actual calendar is not appended in DOM until user clicks on input element. So when we do 

`calendar.update()`

It just messes up and inserts calendar html in place of input element.

Please suggest how can I make it work ?
