### ISSUE TITLE
Error on input initialised calendar after 2.7 update

### ISSUE THREAD

**Issue by andrei-dracea** [uvarov-frontend/vanilla-calendar#138]
I now get an error 
`Uncaught (in promise) TypeError: Cannot read properties of null (reading 'classList') at createDOM (vanilla-calendar.min.mjs:551:19)`

Here seems to be the issue
```
const createDOM = (self, target) => {
    const calendarElement = self.HTMLElement;
    calendarElement.classList.add(self.CSSClasses.calendar);
...
```

**Comment by andrei-dracea** [comment]
Also, after 2.6.4 I have an issue with `.vanilla-calendar` having `max-width: 100%` as it sometimes doesn't fit the content

**Comment by uvarov-frontend** [comment]
Put the code on the sandbox so that I understand where the problem occurs.

**Comment by uvarov-frontend** [comment]
No information provided.
