### ISSUE TITLE
Recreate calendar instance? unlike method 'reset', i want to recreate instance for specific scenario

### ISSUE THREAD

**Issue by arechta** [uvarov-frontend/vanilla-calendar#141]
Is there any method to destroy instance? like this

```javascript
const calendar[0] = new VanillaCalendar(element, config);
calendar[0].destroy(); // Method to destroy current calendar instance
``` 

Thank you for your library, it was very helpful 👋

**Comment by uvarov-frontend** [comment]
There is no such method.
I have no idea why you would need this, but you can remove all child elements using native js.

```
// Initialization
const calendarEl = document.querySelector('#calendar');
let calendar = new VanillaCalendar(calendarEl);
calendar.init();
```

```
// Destruction
calendar = undefined;
calendarEl.innerHTML = '';
```

If this is not enough, you can also remove the added classes and date attributes when initializing the calendar:
```
calendarEl.removeAttribute('data-calendar-theme');
calendarEl.removeAttribute('class');
```

Now, if you need it, you can reinitialize the calendar:
```
calendar = new VanillaCalendar(calendarEl);
calendar.init();
```

Sandbox example: https://codesandbox.io/s/adoring-butterfly-zc6yjj?file=/calendar.js

**Comment by uvarov-frontend** [comment]
In general, I think it’s worth adding a method so that you can destroy a calendar instance.
I will add a `destroy()` method in a future release.
Thanks for the idea.

**Comment by arechta** [comment]
> There is no such method. I have no idea why you would need this, but you can remove all child elements using native js.
> 
> ```
> // Initialization
> let calendarEl = document.querySelector('#calendar');
> let calendar = new VanillaCalendar(calendarEl);
> calendar.init();
> ```
> 
> ```
> // Destruction
> calendar = undefined;
> calendarEl.replaceWith(calendarEl.cloneNode(false));
> ```
> 
> If this is not enough, you can also remove the added classes and date attributes when initializing the calendar:
> 
> ```
> calendarEl.removeAttribute('data-calendar-theme');
> calendarEl.removeAttribute('class');
> ```
> 
> Now, if you need it, you can reinitialize the calendar:
> 
> ```
> calendarEl = document.querySelector('#calendar');
> calendar = new VanillaCalendar(calendarEl);
> calendar.init();
> ```
> 
> Sandbox example: https://codesandbox.io/s/adoring-butterfly-zc6yjj?file=/calendar.js

Thanks for your reply
Yes I am currently using, the method of recreating an element as you suggested

**Comment by arechta** [comment]
is it possible to select the range of months in the calendar? after I read the documentation I didn't find what I was looking for, currently I'm working around it by creating 2 calendar instances, here is the screenshot below
![image](https://github.com/uvarov-frontend/vanilla-calendar/assets/36139976/5494b81d-caf5-4a13-b653-36c972e0cb9e)

**Comment by uvarov-frontend** [comment]
destroy() added in v2.7.1
