### ISSUE TITLE
Using settings.selected.month & settings.selected.year returns incorrect month & year

### ISSUE THREAD

**Issue by btjackson11** [uvarov-frontend/vanilla-calendar#149]
This is an amazing library and has been super easy to use this far! I found an interesting bug when trying to set a specific month/year using settings.selected.month & settings.selected.year. If I am setting this incorrectly please let me know, but this seems like it isn't functioning as expected.

Example Codepen: https://codepen.io/jvckson/pen/gOqRLbW

In this instance I am setting the following:
```
const options = {
  settings: {
    selected: {
      month: '2',
      year: '2023',
    }
  },
};
```

Expected result: Sets calendar to March 2023
Actual result: Sets calendar to September 2024

I have noticed that the months are pretty consistently set as the following:
```
0 = January
1 = November
2 = September
3 = July
4 = May
5 = March
6 = January
7 = November
8 = September
9 = July
10 = May
11 = March
```

As you increase the months the years appear to become increasingly further off and some months aren't able to be returned regardless of value (ex. February). Example where the month value set increases by 1:
```
const options = {
  settings: {
    selected: {
      month: '3',
      year: '2023',
    }
  },
};
```

Expected result: Sets calendar to April 2023
Actual result: Sets calendar to July 2025

**Comment by uvarov-frontend** [comment]
Hi, the values should be a number, not a string.

```
const options = {
  settings: {
    selected: {
      month: 2,
      year: 2023,
    }
  },
};
```

But in any case, it's unforeseen behavior, I'll fix it, thank you.

**Comment by btjackson11** [comment]
Thanks @uvarov-frontend that worked as expected!
