### ISSUE TITLE
Missing reference in types.ts 

### ISSUE THREAD

**Issue by andeeplus** [uvarov-frontend/vanilla-calendar#153]
Hi Yuri,
Really brillant package, clean and easy to use.

I've found an issue in your `type.ts` file in the src of the package.
Looks like you are importing the themes const from a directory that do not exist in the build.

`import themes from './scripts/helpers/getThemes';`

I discover it because while building the json schema of the types in a project I'm working at, I couldn't build it due to the missing ref.

The package works smoothly anyway, also if this issue is causing the auto completion for setting.visibility.themes not being in place.

As a workaround in the meanwhile I've copy/pasted the types I need for my use case and now everything works correctly.

**Comment by uvarov-frontend** [comment]
Hi, fixed in https://github.com/uvarov-frontend/vanilla-calendar/commit/8485e7a2ab6bbc7064db287c98b1f24c8738731f#diff-94dee8f35a0c85594a1b1d54ce08b845aacaca3e1c890f1df05e32eab2c609ec.

Expect a new version that will include this commit.
Thanks for reporting the problem! Have a good day!

**Comment by uvarov-frontend** [comment]
By the way, there is no such problem in v2.7.2, you can use it if you don't want to use your workaround.

**Comment by andeeplus** [comment]
Oh great! Glad to know it, I'll wait the next release then.
Best

**Comment by uvarov-frontend** [comment]
Fixed in v2.8.4
