### ISSUE TITLE
Why do you use the word Vanilla in the project when it's TypeScript?

### ISSUE THREAD

**Issue by blaasvaer** [uvarov-frontend/vanilla-calendar#19]
See title …

You could fix this by ALSO providing a vanilla version ; )

**Comment by uvarov-frontend** [comment]
Because TypeScript is only used for source code, the end result is vanilla js. Prior to version 2.0.0, the sources were written in vanilla js.
Use [latest version without using TypeScript] (https://www.npmjs.com/package/@uvarov.frontend/vanilla-calendar/v/1.5.5)

**Comment by blaasvaer** [comment]
Well, not really an argument, as EVERYTHING finally running in the browser IS vanilla JavaScript. When naming projects, you should refer to what it is WRITTEN in – IF you need to refer to any specific language – as you actually do in this one. In the end it's all machine code ... so if that's your argument a proper name would be: Machine Code Calendar ; )

**Comment by uvarov-frontend** [comment]
If I need help picking a name, I'll contact you, and since I didn't ask for your opinion, we don't have much to talk about right now.
It has become too STUFFY here, perhaps since you have no more questions, I will close the discussion.
