### ISSUE TITLE
Having an issue on getting year and month by clicking on arrows and on page load.

### ISSUE THREAD

**Issue by Habib2959** [uvarov-frontend/vanilla-calendar#20]
I want to get year and month when it changes after clicking the arrows and on page load. Is there any way to get those? Thanks.

**Comment by uvarov-frontend** [comment]
Hi. I previously answered this question in discussions, please take a look. https://codesandbox.io/s/festive-taussig-8bk5hi

**Comment by uvarov-frontend** [comment]
This is not the first time this has come up in discussion. Problem solved in release v2.2.5

**Comment by Habib2959** [comment]
Thanks a lot.
