### ISSUE TITLE
[Feature proposal] Highlighting the date range on hover, before I click to select the second date

### ISSUE THREAD

**Issue by andrei-dracea** [uvarov-frontend/vanilla-calendar#28]
This would be great for UX, as currently there is no way the user can tell when range mode is on.
p.s. great work on the plugin :)

**Comment by uvarov-frontend** [comment]
Hi, great idea, I'll do it in the next issue.

**Comment by andrei-dracea** [comment]
it works nicely, only one issue, when you move your mouse out of the calendar box, if you have NOT selected the second date, the hover highlight should be cleared.. otherwise it looks as if the dates are selected

**Comment by uvarov-frontend** [comment]
Problem found, thanks.
