### ISSUE TITLE
Programmatically change date on the calendar

### ISSUE THREAD

**Issue by giugrilli** [uvarov-frontend/vanilla-calendar#29]
I cannot find anywhere how can I change date/time to the calendar. Some method/event. 
Thank you in advance

**Comment by uvarov-frontend** [comment]
Hello. Please clarify your question. It is not clear where and what date and time you want to change. The [API](https://vanilla-calendar.frontend.uvarov.tech/api/) defines ways to set the date before and after the calendar is initialized using the update() method.
