### ISSUE TITLE
Ability to enable only a range of dates

### ISSUE THREAD

**Issue by Tmeister** [uvarov-frontend/vanilla-calendar#3]
First, thanks for your work.

Will be great if we could select a range of the dates to be enabled; this should be the opposite of `settings.range.disabled` 

My use case is:

There are only three available dates to select in a given month. For example

```
enable: ['2022-01-20', '2022-01-25', '2022-01-26']
```

The docs state that we can use:

```
disabled: ['...', ... ]
```

But, if you want to enable only these there dates we need to pass 27 dates on the `disabled` options instead of 3.

Does this make sense?

**Comment by uvarov-frontend** [comment]
Hey. Thanks for your interest in the plugin. Your idea is great and easy to implement, I will add this feature.

**Comment by uvarov-frontend** [comment]
Added in v1.5.0
