### ISSUE TITLE
[Request] Week number clickable

### ISSUE THREAD

**Issue by Jako** [uvarov-frontend/vanilla-calendar#30]
Thanks for the nice calendar!

I have an idea for an improvement: Make the week number clickable and show the selected week number and/or the displayed week with a bar.

**Comment by uvarov-frontend** [comment]
Hi, okay, I like this idea.

**Comment by uvarov-frontend** [comment]
In version 2.2.7, the [clickWeekNumber](https://vanilla-calendar.frontend.uvarov.tech/api/#actions-clickWeekNumber) method has been added, which allows you to get an array of days in the form of html elements, this allows you to flexibly customize what You need.

As an example: https://codesandbox.io/s/gifted-night-umi0w8
or if you need to assign these days as selected: https://codesandbox.io/s/headless-leftpad-tqrw1h
