### ISSUE TITLE
react

### ISSUE THREAD

**Issue by rhsok** [uvarov-frontend/vanilla-calendar#32]
const calendar = new VanillaCalendar(calendarEl.current, {
            settings: {
                lang: 'en',
                selection: {
                    time: 12,
                },
            },
        });
        console.log(calendar.settings);
        calendar.init();
    }, [calendarEl]);
    
   ## 'VanillaCalendar<HTMLDivElement, { settings: { lang: string; selection: { time: number; }; }; }>' 형식에 'settings' 속성이 없습니다.
    
   ## I want to get the value of calendar.settings.slected.dates.
    
   ##  I get the value, but I keep getting a type error. Can you tell me how to solve it?

**Comment by uvarov-frontend** [comment]
Пожалуйста, используйте метод `clickDay`, для получения выбранных дат.
```
actions: {
  clickDay(e, dates) {
    calendarInfoDate.innerText = dates[0] ? dates : '«Day not selected»';
  },
```
