### ISSUE TITLE
Show additional days if month ends on a Sunday (Saturday with ISO8601)

### ISSUE THREAD

**Issue by TheKruspe** [uvarov-frontend/vanilla-calendar#5]
I am using this project to let customers select a day to book an appointment. If on the 31st, there are no time slots available today, the customer needs to select another date - that's most probably tomorrow. If the current month ends on a Sunday, the user has to click to the next month in order to select another date. It would be very convenient to maybe have one more week listed below. If a user clicks one of them, it could automatically turn to the next month.

**Comment by uvarov-frontend** [comment]
Hi. I'll think about it, thanks.
