### ISSUE TITLE
Custom lang doesn't work with monts

### ISSUE THREAD

**Issue by agustinglez** [uvarov-frontend/vanilla-calendar#7]
Hi!

If you set your custom "language", months return "undefined" with this config in Docs

`new VanillaCalendar('#calendar', {
  settings: {
    lang: 'define',
  },
  locale: {
    months: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
  },
});`

![image](https://user-images.githubusercontent.com/1512393/185155126-d1610a63-86fb-48e2-85b0-983f9308733d.png)

**Comment by uvarov-frontend** [comment]
Hi, if you set your settings.lang to 'define', you need to specify your locale not only for months but also for weeks.
```
new VanillaCalendar('#calendar', {
  settings: {
    lang: 'define',
  },
  locale: {
    months: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
    weekday: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
  },
});
```

**Comment by agustinglez** [comment]
Yes, I did it, but doesn't work

![image](https://user-images.githubusercontent.com/1512393/185157629-8cba0839-c8bd-4106-bbfb-d747c2f278b0.png)

**Comment by uvarov-frontend** [comment]
Your "locale" must be outside of "settings"

**Comment by agustinglez** [comment]
You're right. My bad, sorry. I didn't sleep well.
