### ISSUE TITLE
Calendar not updating disabled or selected dates

### ISSUE THREAD

**Issue by ddegroot1985** [uvarov-frontend/vanilla-calendar#77]
According to the documentation (https://vanilla-calendar.com/docs/reference/main/initialize-and-update) the settings can be updated and applied using the `update` method.

I tried to update the disabled and selected dates but it does not seem to be doing anything, see here:

https://codesandbox.io/s/brave-thunder-4gegn7?file=/calendar.js

Edit: Issue is only with 2.5.7, after downgrading to 2.5.6 it works as expected.

**Comment by uvarov-frontend** [comment]
Fixed in v2.5.8
Now you can update the calendar with the new settings using the `update()` or `reset()` method.
The `update()` method, unlike `reset()`, saves the user's selected dates, month, and year after the update.
