### ISSUE TITLE
Popup's dates only show in current month

### ISSUE THREAD

**Issue by agustinglez** [uvarov-frontend/vanilla-calendar#8]
Hi there, It's me again.
Following the same example in Docs, I want to set a popup in multiples dates across the year, but the script only show these marked days in the current month, if you click in next month, doesn't show at all.

I create a sandbox with an example: [https://w2ot96.csb.app/](https://w2ot96.csb.app/)

Only show dates in August but in September doesn't show anything.

**Comment by agustinglez** [comment]
I just solved with this fix:

```
createPopup(daysEl) {
		if (!this.popups) return;

		// eslint-disable-next-line no-restricted-syntax
		for (const day in this.popups) {
			if (Object.hasOwnProperty.call(this.popups, day)) {
				const dayBtnEl = daysEl.querySelector(`[data-calendar-day="${day}"]`);
				//if (!dayBtnEl) return;

				if (dayBtnEl){
					const dayInfo = this.popups[day];
					dayBtnEl.classList.add(dayInfo.modifier);
					dayBtnEl.parentNode.innerHTML += `<div class="vanilla-calendar-day__popup">${dayInfo.html}</div>`;
				}
			}
		}
	}
```

I hope this help.

**Comment by uvarov-frontend** [comment]
Thanks for reporting the issue! 👍
