### ISSUE TITLE
Npm package install error

### ISSUE THREAD

**Issue by mliebaut** [uvarov-frontend/vanilla-calendar#86]
Hello, I tried to install the package with npm, but I have a parsing error due to the "@" symbol, here is the error I translated in english: 

```
+ npm install @uvarov.frontend/vanilla-calendar
+ ~~~~~~~
Cannot use the "@" projection operator to reference variables in an expression. “@uvarov” can only be used as an argument to a command. To reference variables
in an expression, use “$uvarov”.
    + CategoryInfo: ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId: SplattingNotPermitted
```

Do someone have an idea of what can I do ? Thank you

**Comment by uvarov-frontend** [comment]
Maybe you are using powershell in windows.
In this case, you need to wrap the name in quotes, like this:
`npm install "@uvarov.frontend/vanilla-calendar"`

**Comment by mliebaut** [comment]
yep thank you I did not think about it !
