### ISSUE TITLE
How about showing today by local time rather than UTC?

### ISSUE THREAD

**Issue by leenzhu** [uvarov-frontend/vanilla-calendar#9]
Hi,

My current timezone is `UTC+08` when I set my system time to `2022-08-31 03:00`, I think the date today should be `31`, but vanilla-calendar shows the date of today is `30`. 

After reading the code, I found it uses UTC date as today:

https://github.com/uvarov-frontend/vanilla-calendar/blob/b95971625bc649d6327b77e776570ad2194e42f4/src/vanilla-calendar.js#L452-L462

I think it would be more friendly if it shows today by local timezone.

**Comment by uvarov-frontend** [comment]
Hello! Thanks for reporting the issue, I'll fix it in the next release.

**Comment by uvarov-frontend** [comment]
Issue fixed in version 2.0.0
