### ISSUE TITLE
Enlarge the entire component

### ISSUE THREAD

**Issue by RootofalleviI** [uvarov-frontend/vanilla-calendar#93]
Hello there!

Thank you so much for creating this fantastic library.

I have two questions: 
- Would you mind showing me the right way of enlarging the entire component? Currently, the `vanilla-calendar` class has a height and width set to max-content. I'm interested in scaling everything to be slightly larger so that I can add decorations to each date (for example, displaying icons or text next to the date number). 
- Would you mind showing me the right way of decorating (or replacing) each date (currently represented as `button` elements) on the component?

Thank you in advance!

**Comment by sengiv** [comment]
>Would you mind showing me the right way of enlarging the entire component? Currently, the vanilla-calendar class has a height and width set to max-content. I'm interested in scaling everything to be slightly larger....

You can use CSS to scale the entire component. The transform: scale() property in CSS allows you to adjust the size of an element and its content. This includes padding and border.

Here's an example of how you can use it:
```CSS
.vanilla-calendar {
    transform: scale(1.2) !important;
    transform-origin: top left !important;
}
```
Please note that the transform: scale() property scales an element from its center by default. If you want to scale it from a different point, you can use the transform-origin property.  This will scale the element from its top left corner.

Remember to test your changes across different browsers and devices to ensure that your scaling looks good everywhere.

**Below is working example screenshot**
## NORMAL
![2023-07-27 10_41_35-](https://github.com/uvarov-frontend/vanilla-calendar/assets/43817262/f73f43ec-c4f2-46ec-9f78-05af23fa0630)
## SCALED x1.2
![2023-07-27 10_37_19-Add New Person Profile](https://github.com/uvarov-frontend/vanilla-calendar/assets/43817262/baf15821-0b7d-49c6-946a-2f48f41ae9b0)

**Comment by uvarov-frontend** [comment]
Hi, this discussion is not related to the work of the plugin, it is better to ask such questions on stackoverflow.com, I hope for understanding.
