### ISSUE TITLE
SyntaxError : "i" has already been declared (only for version 2.5.0 and above) 

### ISSUE THREAD

**Issue by sengiv** [uvarov-frontend/vanilla-calendar#94]
![image](https://github.com/uvarov-frontend/vanilla-calendar/assets/43817262/deec4ca8-41de-4304-a567-d34da6b75dd7)

One version below `2.5.0` is `2.4.0` which works perfectly.
All versions after` 2.4.0 `till `2.6.1` has this error
Is this a bug?

**Comment by uvarov-frontend** [comment]
Hi. How do I reproduce this problem? Put the code on codesandbox.
