### ISSUE TITLE
In US our calendars go sun-sat

### ISSUE THREAD

**Issue by ChristopherTheBoss** [uvarov-frontend/vanilla-calendar#96]
> Sun Mon Tues Wed Thurs Fri Sat

yours goes 

> Mon Tues Wed Thurs Fri Sat Sun

there's an option that I assumed would fix this:
`locale: {
    weekday: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
  }
but alas it does not.

**Comment by uvarov-frontend** [comment]
https://vanilla-calendar.com/docs/learn/internationalization/iso-8601
