### ISSUE TITLE
Standard action executed after hook

### ISSUE THREAD

**Issue by Ariel-International** [uvarov-frontend/vanilla-calendar#97]
If I set an action for ClickDay() I don't want to execute the standard select/deselect action afterwards.
But if I set day selection to false, the event doesn't fire.
There should be a way to perform action without executing standard events.
Returning false from ClickDay() should do the trick IMHO.

**Comment by uvarov-frontend** [comment]
Set `settings.selection.day` to `false` and add your own day click handler.

**Comment by Ariel-International** [comment]
Hello!
Thank you for answering.
I'll try again, that's exactly what I did.
Or at least I think so.
 
const options = {
    type: 'multiple',

    actions: {
        clickDay(e, dates) {console.log(e, dates); },
    },    
    settings: {
        selection: {
        day: false,
        },
/*        selected: {
        dates: ['2023-08-09:2023-08-13', '2023-08-22'],
        }, */
    },
    CSSClasses: {
        weekDayWeekend: 'cal-we',
        dayBtnWeekend: 'cal-we',
    },
    popups: {
        '2023-08-28': {
        modifier: 'bg-red color-pink',
        html: `<div>
            <u><b>12:00 PM</b></u>
            <p style="margin: 5px 0 0;">Airplane in Las Vegas</p>
        </div>`, // or just text 'Airplane in Las Vegas'
        },
    }
};
const calendar = new VanillaCalendar('#calendar', options);
calendar.init();
</script>
 

Cordialmente,

Stefano Bonvini

Ariel.international ltd

**Comment by Ariel-International** [comment]
I confirm it does not fire if I set settings.selection.day to false.
I cleaned a bit, changed the order of parameters, nothing works.
If I set to 'multiple' it works regularly, but of course it does the standard action.

**Comment by Ariel-International** [comment]
I still think the best thing would be to execute tasks based on a return flag from ClickDay() action, so one could choose any selection.day and execute it based on the outcome of the custom function.
Of course I don't even know what I'm talking about, in terms of implementation, so thank you for all you do.

**Comment by uvarov-frontend** [comment]
Write to me in telegram and describe what you want, I'll try to help you. I'll answer in the morning in Moscow.

**Comment by uvarov-frontend** [comment]
Don't use the `clickDay()` action unless you want to use its default action.

As I wrote above, you need to disable the day selection and add your own click handler in the calendar.

For example, like this:
```
const calendarEl = document.querySelector("#calendar");

const options = {
  settings: {
    selection: {
      day: false
    }
  }
  // actions: {
  //   clickDay(event, dates) {
  //     console.log(dates);
  //   },
  // },
};

const calendar = new VanillaCalendar(calendarEl, options);
calendar.init();

calendarEl.addEventListener("click", (e) => {
  const btn = e.target.closest("[data-calendar-day]");
  if (!btn) return;
  console.log(btn);
});

```
Example on [codesandbox](https://codesandbox.io/s/sleepy-sunset-dfcxd6?file=/calendar.js)

**Comment by Ariel-International** [comment]
Ooh, I see, "my own click handler"!
This is clear now, thank you for the clarification.
Maybe in the future you can plan to include this directly in the library, by firing click Day() also when selection.day is false, or in this case based on the return value of clickDay(), if possible.
But now I can work with it and I'm happy.
Thank you!
