### ISSUE TITLE
Отображение дополнительной информации в дне календаря. 

### ISSUE THREAD

**Issue by mihailbishkek** [uvarov-frontend/vanilla-calendar#98]
Подскажите пожалуйста, как можно сделать отображение какой-либо информации в каком либо из дней календаря? 

К примеру - у меня есть массив из дат, и минимальных цен на эти даты. Как можно было бы сразу визуально в календаре под каждым из дней выводить минимальную цену на этот день?

**Comment by uvarov-frontend** [comment]
Добавлен новый `actions` позволяющий получить необходимую информацию и  html-элемент каждого дня.

**Comment by uvarov-frontend** [comment]
https://vanilla-calendar.com/ru/docs/learn/action-handlers/get-and-change-every-day
